config/routes.rb
Rails.application.routes.draw do
  resources :events

  root 'events#index'

end

app/models/event.rb
# Describes the Event
class Event < ActiveRecord::Base
  mount_uploader :cover_img, CoverImgUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
# Handles logic for the events controller
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :password_check, only: [:edit, :update, :destroy, :new]

  # GET /events
  def index
    @events = Event.all.order(start_date: :asc)
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Event was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          redirect_to @event, notice: 'Event was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html do
        redirect_to events_url, notice: 'Event was successfully destroyed.'
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def password_check
    redirect_to action: :index unless params[:password] == 'trustno1'
  end

  # Never trust parameters from the scary internet
  def event_params
    params.require(:event).permit(
      :title, :category_id, :start_date, :end_date,
      :teaser, :description, :cover_img, :street_no, :street_name, :floor,
      :town, :region, :postcode, :country, :venue_name, :password
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end

  def meta_tag(tag, text)
    content_for :"meta_#{tag}", text
  end

  def yield_meta_tag(tag, default_text= '')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event, html:{multipart: true} do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category_id
    = f.number_field :category_id
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :teaser
    = f.text_field :teaser
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :cover_img
    = f.file_field :cover_img
  .field
    = f.label :venue_name
    = f.text_field :venue_name
  .field
    = f.label :street_no
    = f.text_field :street_no
  .field
    = f.label :street_name
    = f.text_field :street_name
  .field
    = f.label :floor
    = f.text_field :floor
  .field
    = f.label :town
    = f.text_field :town
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :postcode
    = f.text_field :postcode
  .field
    = f.label :country
    = f.text_field :country
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
.container
  .row
    .col-sm-12.event-index-news
      .alert.alert-info
        %h4 Add your event to the list.
        %p
          We'd love you list your event on this site, for free.
          Drop an email to mark@m12n.co.uk with the details.

  .row
    .col-sm-12
      %h2 Upcoming Events

  .row
  - @events.each do |event|
    .col-xs-12.col-sm-6.col-md-6.col-lg-4
      .listing{style:"background: #fff url(#{event.cover_img}) no-repeat center top;background-size: cover;"}
        .info-block
          .headerblock
            =link_to(event.title, event)
            %span.listing-title-location
              -if (event.region.length > 1)
                %span
                  %i.fa.fa-map-marker
                  =event.region
          .footerblock
            .listing-date
              %i.fa.fa-calendar
              =event.start_date.strftime("%d/%m/%Y")
            -#.listing-icons
              %i.fa.fa-eye
              100

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
- title(@event.title)
- meta_tag("og:url", event_url(@event))
- meta_tag("og:description", @event.teaser)
- meta_tag("og:image", @event.cover_img)
- meta_tag("og:title", @event.title)

.event-show-container
  .event-show-header{style:"background: #fff url(#{@event.cover_img});"}
    .container.event-show-content
      .row
        .col-md-4.offset-md-4
          .event-show-meta
            .h1
              = @event.title
            %span.show-location{style:"width:100%;border-bottom: solid 1px rgba(255,255,255,0.2);float: left;"}
              -if (@event.region.length > 1)
                %span
                  %i.fa.fa-map-marker
                  =@event.region
            .row
              .col-xs-6
                %span.meta-text
                  Starts:
                %span.meta-icon
                  %i.fa.fa-calendar
                %span.meta-text
                  =@event.start_date.strftime("%d/%m/%Y")
                %span.meta-icon
                  %i.fa.fa-clock-o
                %span.meta-text
                  =@event.start_date.strftime("%H:%M")
              .col-xs-6
                %span.meta-text
                  Ends:
                %span.meta-icon
                  %i.fa.fa-calendar
                %span.meta-text
                  =@event.end_date.strftime("%d/%m/%Y")
                %span.meta-icon
                  %i.fa.fa-clock-o
                %span.meta-text
                  =@event.end_date.strftime("%H:%M")
  .container
    .event-show-details
      .detail-dash
      .details-main
        .row
          .col-sm-12
            .section-header
              %h3
                %span
                  %i.fa.fa-info-circle
                  Event Details
            .section-detail
              .row
                .col-sm-6
                  %p
                    =simple_format(@event.teaser)
                  %p
                    =simple_format(@event.description)
                .col-sm-6
                  %span.address-block
                    %i.fa.fa-map-marker
                    %span.address-text
                      %h5
                        =@event.venue_name
                      %address
                        = "#{@event.street_no} #{@event.street_name}"
                        %br
                        -if (@event.floor.length > 0)
                          = "Floor #{@event.floor}"
                          %br
                        -if (@event.town.length > 0)
                          = @event.town
                          %br
                        -if (@event.region.length > 0)
                          = @event.region
                          %br
                        -if (@event.postcode.length > 0)
                          = @event.postcode
                          %br
                        -if (@event.country.length > 0)
                          = @event.country
                          %br
    .row
      .col.sm-12
        .event-show-btm-nav
          =link_to 'Back', events_path, class:"btn btn-primary"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title
    = if content_for?(:title) then yield(:title) + ' | ' end
    Chatbot.Events
  %meta{ :property => 'og:title', :content => "#{yield_meta_tag('og:title', 'Chatbot.Events')}" }
  %meta{ :property => 'og:site_name', :content => "#{yield_meta_tag('og:site_name', 'Chatbot.Events')}" }
  %meta{ :property => 'og:url', :content => "#{yield_meta_tag('og:url', 'http://www.chatbot.events')}" }
  %meta{ :property => 'og:description', :content => "#{yield_meta_tag('og:description', 'Find events relating to Chatbots')}" }
  %meta{ :property => 'og:image', :content => "#{yield_meta_tag('og:image', image_url('Logo-Layout.png'))}" }
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-fixed-top
    .container
      %a.navbar-brand{href:"#"}
        = image_tag("logo_small.png", height: 50, class:"pull-left")
        %h1.pull-left.logo
          CHATBOT.EVENTS
      -#.navbar-items.pull-right
        %button.navbar-toggler.hidden-sm-up{type:"button", data:{toggle:"collapse", target:"#nav"}, aria:{controls:"nav", expanded:"false", label:"Toggle Navigation"}}
          &#9776;
        .collapse.navbar-toggleable-xs{id:"nav"}
          %a.nav-item.nav-link.active{href:"#"}
            Home
            %span.sr-only
              (current)
          %a.nav-item.nav-link{href:"#"}
            Features
  = yield